{
 "title": "K8S Cluster Deployments",
 "description": "Dashboard that shows how many deployments occurred by namespace or in the cluster and your workload",
 "tags": [
  "k8s",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_replicaset_created{job=\"kube-state-metrics\"} , exported_namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{job=\"kube-state-metrics\", exported_namespace=\"$namespace\"} , deployment)"
   },
   {
    "name": "replicaset",
    "label": "ReplicaSet",
    "query": "query_result(topk(1, kube_replicaset_created{job=\"kube-state-metrics\", exported_namespace=\"$namespace\", replicaset=~\"$deployment-[0-9a-fA-F]+\"}))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Latest Deployment $namespace / $replicaset</span>\n</div>"
  },
  {
   "title": "Last  deployments in $namespace / $deployment",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sort_desc(sum((kube_replicaset_created{job=\"kube-state-metrics\", exported_namespace=\"$namespace\", replicaset=~\"$deployment-[0-9a-fA-F]+\"}) * 1000) by (replicaset, exported_namespace))"
    }
   ]
  },
  {
   "title": "Deployments in $deployment (last day)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kube-state-metrics\",exported_namespace=\"$namespace\",replicaset=~\"$deployment.*\"} > time() - 86400))"
    }
   ]
  },
  {
   "title": "Deployments in $deployment (7 days)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kube-state-metrics\",exported_namespace=\"$namespace\",replicaset=~\"$deployment.*\"} > time() - 604800))"
    }
   ]
  },
  {
   "title": "Deployments in $deployment (last month)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kube-state-metrics\",exported_namespace=\"$namespace\",replicaset=~\"$deployment.*\"} > time() - 2592000))"
    }
   ]
  },
  {
   "title": "Last deployments workload stats in $deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Stats  - $namespace / $deployment",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\", pod_name=~\"$deployment-[0-9a-fA-F].*\"}) by (pod_name, pod_container_name) / 1000",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Memory Stats - $namespace / $deployment",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\", pod_name=~\"$deployment-[0-9a-fA-F].*\"}) by (pod_name, pod_container_name) / 1000",
       "legendFormat": "{{ pod_name }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Last deployments in $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Deployments in $namespace",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sort_desc(sum((kube_replicaset_created{job=\"kube-state-metrics\",exported_namespace=\"$namespace\"} > time() - 604800) * 1000) by (replicaset,exported_namespace))"
      }
     ]
    },
    {
     "title": "Deployments in $namespace (last day)",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count((kube_replicaset_created{job=\"kube-state-metrics\",exported_namespace=\"$namespace\"} > time() - 86400))"
      }
     ]
    },
    {
     "title": "Deployments in $namespace (last 7 days)",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count((kube_replicaset_created{job=\"kube-state-metrics\",exported_namespace=\"$namespace\"} > time() - 604800))"
      }
     ]
    },
    {
     "title": "Deployments in $namespace (last month)",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count((kube_replicaset_created{job=\"kube-state-metrics\",exported_namespace=\"$namespace\"} > time() - 2592000))"
      }
     ]
    }
   ]
  },
  {
   "title": "Last deployments in Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Deployments in Cluster",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(((kube_replicaset_created{job=\"kube-state-metrics\"} > time() - 604800) * 1000)) by (replicaset, exported_namespace)",
       "legendFormat": "{{ exported_namespace }} - {{ replicaset }}"
      },
      {
       "expr": "sum(((kube_statefulset_created{job=\"kube-state-metrics\"} > time() - 604800) * 1000)) by (statefulset, exported_namespace)",
       "legendFormat": "{{ exported_namespace }} - {{ statefulset }}"
      },
      {
       "expr": "sum(((kube_daemonset_created{job=\"kube-state-metrics\"} > time() - 604800) * 1000)) by (daemonset, exported_namespace)",
       "legendFormat": "{{ exported_namespace }} - {{ daemonset }}"
      }
     ]
    },
    {
     "title": "Deployments in last day",
     "type": "singlestat",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 13 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(({__name__=~\"kube_replicaset_created|kube_statefulset_created|kube_daemonset_created\", job=\"kube-state-metrics\"} > time() - 86400))"
      }
     ]
    },
    {
     "title": "Deployments in last 7 days",
     "type": "singlestat",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 13 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(({__name__=~\"kube_replicaset_created|kube_statefulset_created|kube_daemonset_created\", job=\"kube-state-metrics\"} > time() - 604800))"
      }
     ]
    },
    {
     "title": "Deployments in last month",
     "type": "singlestat",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 13 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(({__name__=~\"kube_replicaset_created|kube_statefulset_created|kube_daemonset_created\", job=\"kube-state-metrics\"} > time() - 2592000))"
      }
     ]
    }
   ]
  }
 ]
}